### ISSUE TITLE
Still maintained

### ISSUE THREAD

**Issue by AMHOL** [marcy/csquery#1]
Hi, I was just wondering whether this library is still maintained as there hasn't been any activity in a while, I have a couple of PRs I want to submit but don't want to put the work in unnecessarily.

**Comment by marcy** [comment]
Since I want to maintain it, PR is welcome.

**Comment by AMHOL** [comment]
Thanks @marcy :smile:

**Comment by AMHOL** [comment]
@marcy 

* https://github.com/marcy/csquery/pull/2
* https://github.com/marcy/csquery/pull/3

:smile:
